# This module sets the default settings

import xml.dom.minidom
import codecs

def set_default(version):
        domtree = xml.dom.minidom.Document()
        settings = domtree.createElement('settings')
        settings.setAttribute('version', version)

        tasks(domtree, settings)
        break_settings(domtree, settings)
        workers_minimum(domtree, settings)
        breaks_length(domtree, settings)
        excel_templates(domtree, settings)
        excel_selected(domtree, settings)

        domtree.appendChild(settings)

        domtree.writexml(codecs.open('settings.xml', "w", "utf-8"), encoding="utf-8")

        return domtree


def tasks(domtree, settings):

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '1')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('Kassa'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('e4b803'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('780'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('10'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '2')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('Rast'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('000000'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('780'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('10'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '3')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('Arbetsledning'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('1104b3'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('false'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('false'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('780'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('10'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '4')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('Förbutik'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('780495'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('false'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('780'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('10'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '5')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('SCO'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('0c8d1c'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('60'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('3'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)

        new_task = domtree.createElement('task')
        new_task.setAttribute('id', '6')
        name = domtree.createElement('name')
        name.appendChild(domtree.createTextNode('PSS'))
        new_task.appendChild(name)
        color = domtree.createElement('color')
        color.appendChild(domtree.createTextNode('c86104'))
        new_task.appendChild(color)
        auto_generate = domtree.createElement('auto_generate')
        auto_generate.appendChild(domtree.createTextNode('false'))
        new_task.appendChild(auto_generate)
        default_certified = domtree.createElement('default_certified')
        default_certified.appendChild(domtree.createTextNode('true'))
        new_task.appendChild(default_certified)
        schedule_length = domtree.createElement('schedule_length')
        schedule_length.appendChild(domtree.createTextNode('60'))
        new_task.appendChild(schedule_length)
        schedule_max_times = domtree.createElement('schedule_max_times')
        schedule_max_times.appendChild(domtree.createTextNode('3'))
        new_task.appendChild(schedule_max_times)
        settings.appendChild(new_task)


def break_settings(domtree, settings):
    new = domtree.createElement('break')
    minimum = domtree.createElement('min')
    minimum.appendChild(domtree.createTextNode('60'))
    new.appendChild(minimum)
    maximum = domtree.createElement('max')
    maximum.appendChild(domtree.createTextNode('180'))
    new.appendChild(maximum)
    settings.appendChild(new)


def workers_minimum(domtree, settings):

        new = domtree.createElement('workers_minimum')
        data = domtree.createElement('h8')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h9')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h10')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h11')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h12')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h13')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h14')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h15')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h16')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h17')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h18')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h19')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        data = domtree.createElement('h20')
        data.appendChild(domtree.createTextNode('3'))
        new.appendChild(data)
        settings.appendChild(new)


def breaks_length(domtree, settings):

        new = domtree.createElement('workingtime')
        data = domtree.createElement('h4')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h5')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h6')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h7')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h8')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h9')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h10')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h11')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('0'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h12')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h13')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h14')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        new.appendChild(data)
        data = domtree.createElement('h15')
        data2 = domtree.createElement('first_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('second_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        data2 = domtree.createElement('third_break')
        data2.appendChild(domtree.createTextNode('15'))
        data.appendChild(data2)
        data2 = domtree.createElement('forth_break')
        data2.appendChild(domtree.createTextNode('30'))
        data.appendChild(data2)
        new.appendChild(data)
        settings.appendChild(new)


def excel_templates(domtree, settings):

        # excell footer template
        excell = domtree.createElement('excell')
        excell.setAttribute('id', '1')
        excell_title = domtree.createElement('title')
        excell_title.appendChild(domtree.createTextNode('Default'))
        excell.appendChild(excell_title)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'O:1')
        excell_cell.setAttribute('font', 'calibri')
        excell_cell.setAttribute('font_size', '14')
        excell_cell.setAttribute('font_style_bold', 'True')
        excell_cell.setAttribute('fg', '000000')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_left', 'thin')
        excell_cell.setAttribute('border_top', 'thin')
        excell_cell.appendChild(domtree.createTextNode('Tänk på att vi inväntar varandra ifrån rasterna'))
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'P:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Q:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'R:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'S:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'T:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'P:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'U:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'V:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'W:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'X:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Y:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Z:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AA:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AB:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AC:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AD:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AE:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AF:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AG:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AH:1')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_top', 'thin')
        excell_cell.setAttribute('border_right', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'O:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_left', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'P:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Q:2')
        excell_cell.setAttribute('bg', 'FF0000')
        excell_cell.setAttribute('font', 'calibri')
        excell_cell.setAttribute('font_size', '14')
        excell_cell.setAttribute('font_style_bold', 'True')
        excell_cell.setAttribute('fg', '000000')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.appendChild(domtree.createTextNode('Den som kommer tillbaka ifrån sin rast'))
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'R:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'S:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'T:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'U:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'V:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'W:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'X:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Y:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Z:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AA:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AB:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AC:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AD:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AE:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AF:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AG:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AH:2')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_right', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'O:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_left', 'thin')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'P:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Q:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'R:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'S:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell_cell.setAttribute('font', 'calibri')
        excell_cell.setAttribute('font_size', '14')
        excell_cell.setAttribute('font_style_bold', 'True')
        excell_cell.setAttribute('fg', '000000')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.appendChild(domtree.createTextNode('löser den som ska gå på rast.'))
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'T:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'U:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'V:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'W:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'X:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Y:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'Z:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AA:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AB:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AC:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AD:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AE:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AF:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AG:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell.appendChild(excell_cell)
        excell_cell = domtree.createElement('cell')
        excell_cell.setAttribute('id', 'AH:3')
        excell_cell.setAttribute('bg', 'FFFF0000')
        excell_cell.setAttribute('border_bottom', 'thin')
        excell_cell.setAttribute('border_right', 'thin')
        excell.appendChild(excell_cell)
        settings.appendChild(excell)


def excel_selected(domtree, settings):

        excel_selected = domtree.createElement('excel_selected')
        excel_selected.setAttribute('id', '1')
        settings.appendChild(excel_selected)
